### ISSUE TITLE
No connection available

### ISSUE THREAD

**Issue by cmcvip** [Particle-Network/particle-connect-android#2]
createPairing error: com.walletconnect.android.internal.common.exception.NoRelayConnectionException: No connection available
                                                                                                    	at com.walletconnect.android.internal.common.json_rpc.domain.JsonRpcInteractor.checkConnectionWorking(JsonRpcInteractor.kt:66)
                                                                                                    	at com.walletconnect.android.internal.common.json_rpc.domain.JsonRpcInteractor.subscribe(JsonRpcInteractor.kt:234)
                                                                                                    	at com.walletconnect.android.internal.common.model.type.JsonRpcInteractorInterface$DefaultImpls.subscribe$default(JsonRpcInteractorInterface.kt:17)
                                                                                                    	at com.walletconnect.android.pairing.engine.domain.PairingEngine.create(PairingEngine.kt:120)
                                                                                                    	at com.walletconnect.android.pairing.client.PairingProtocol.create(PairingProtocol.kt:42)
                                                                                                    	at org.walletconnect.ConnectLogic.connectToWallet(SourceFile:3)
                                                                                                    	at org.walletconnect.ConnectLogic.connectToWallet$default(SourceFile:1)
                                                                                                    	at com.wallet.connect.adapter.BaseWalletConnectAdapter.connect(SourceFile:91)
                                                                                                    	at com.x3live.wallet.connect.WalletConnectManager.connectMetaMask(WalletConnectManager.kt:34)
                                                                                                    	at com.x3live.wallet.ConnectWalletActivity$setListener$2.invoke(ConnectWalletActivity.kt:108)
                                                                                                    	at com.x3live.wallet.ConnectWalletActivity$setListener$2.invoke(ConnectWalletActivity.kt:103)
                                                                                                    	at com.x3live.common.ext.DebounceClickListener.onClick(SyntaxExtand.kt:233)
                                                                                                    	at android.view.View.performClick(View.java:7506)
                                                                                                    	at android.view.View.performClickInternal(View.java:7483)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:29335)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by cmcvip** [comment]
Why do I sometimes connect to metamask like this

**Comment by cmcvip** [comment]
发现必须得翻墙是吗
